### ISSUE TITLE
[GBC] Simpsons THOH Glitching

### ISSUE THREAD

**Issue by mddifilippo89** [frederic-mahe/Analogue-Pocket#65] opened 2022-02-09 04:38 UTC
https://i.imgur.com/C6t1Yih.gifv

**Comment by manksalot** [comment] 2022-02-10 14:23
Looks like a duplicate of #42

**Comment by francoiswnel** [comment] 2022-08-02 10:10
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta

**Comment by frederic-mahe** [comment] 2022-08-03 07:19
thanks @francoiswnel

**Closed as completed by frederic-mahe** 2022-08-03 07:19 UTC
Labels: GBC, needs confirmation
